name: Email Step Cache Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Prime the cache with a specific key
      - name: prime-cache-62fe6e2
        id: prime-cache-62fe6e2
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: cache-62fe6e2

      # Echo cache hit/miss
      - name: Show cache result
        run: echo "Cache hit? ${{ steps.prime-cache-62fe6e2.outputs.cache-hit }}"
